rm /Volumes/rliu/jedisim_grid/trial_0/trial0_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_0/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_1/trial1_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_1/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_2/trial2_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_2/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_3/trial3_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_3/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_4/trial4_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_4/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_5/trial5_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_5/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_6/trial6_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_6/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_7/trial7_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_7/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_8/trial8_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_8/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_9/trial9_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_9/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_10/trial10_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_10/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_11/trial11_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_11/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_12/trial12_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_12/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_13/trial13_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_13/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_14/trial14_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_14/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_15/trial15_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_15/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_16/trial16_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_16/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_17/trial17_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_17/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_18/trial18_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_18/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_19/trial19_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_19/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_20/trial20_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_20/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_21/trial21_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_21/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_22/trial22_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_22/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_23/trial23_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_23/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_24/trial24_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_24/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_25/trial25_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_25/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_26/trial26_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_26/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_27/trial27_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_27/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_28/trial28_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_28/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_29/trial29_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_29/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_30/trial30_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_30/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_31/trial31_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_31/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_32/trial32_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_32/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_33/trial33_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_33/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_34/trial34_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_34/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_35/trial35_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_35/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_36/trial36_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_36/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_37/trial37_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_37/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_38/trial38_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_38/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_39/trial39_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_39/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_40/trial40_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_40/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_41/trial41_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_41/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_42/trial42_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_42/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_43/trial43_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_43/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_44/trial44_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_44/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_45/trial45_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_45/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_46/trial46_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_46/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_47/trial47_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_47/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_48/trial48_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_48/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_49/trial49_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_49/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_50/trial50_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_50/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_51/trial51_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_51/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_52/trial52_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_52/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_53/trial53_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_53/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_54/trial54_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_54/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_55/trial55_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_55/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_56/trial56_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_56/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_57/trial57_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_57/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_58/trial58_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_58/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_59/trial59_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_59/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_60/trial60_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_60/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_61/trial61_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_61/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_62/trial62_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_62/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_63/trial63_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_63/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_64/trial64_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_64/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_65/trial65_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_65/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_66/trial66_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_66/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_67/trial67_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_67/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_68/trial68_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_68/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_69/trial69_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_69/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_70/trial70_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_70/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_71/trial71_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_71/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_72/trial72_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_72/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_73/trial73_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_73/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_74/trial74_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_74/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_75/trial75_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_75/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_76/trial76_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_76/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_77/trial77_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_77/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_78/trial78_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_78/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_79/trial79_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_79/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_80/trial80_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_80/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_81/trial81_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_81/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_82/trial82_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_82/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/trial_83/trial83_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/trial_83/convolved/convolved_band*.fits 
