rm /Volumes/rliu/jedisim_grid/trial_0/trial0_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_0/90_trial0_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_1/trial1_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_1/90_trial1_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_2/trial2_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_2/90_trial2_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_3/trial3_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_3/90_trial3_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_4/trial4_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_4/90_trial4_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_5/trial5_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_5/90_trial5_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_6/trial6_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_6/90_trial6_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_7/trial7_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_7/90_trial7_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_8/trial8_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_8/90_trial8_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_9/trial9_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_9/90_trial9_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_10/trial10_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_10/90_trial10_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_11/trial11_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_11/90_trial11_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_12/trial12_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_12/90_trial12_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_13/trial13_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_13/90_trial13_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_14/trial14_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_14/90_trial14_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_15/trial15_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_15/90_trial15_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_16/trial16_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_16/90_trial16_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_17/trial17_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_17/90_trial17_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_18/trial18_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_18/90_trial18_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_19/trial19_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_19/90_trial19_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_20/trial20_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_20/90_trial20_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_21/trial21_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_21/90_trial21_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_22/trial22_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_22/90_trial22_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_23/trial23_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_23/90_trial23_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_24/trial24_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_24/90_trial24_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_25/trial25_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_25/90_trial25_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_26/trial26_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_26/90_trial26_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_27/trial27_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_27/90_trial27_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_28/trial28_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_28/90_trial28_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_29/trial29_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_29/90_trial29_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_30/trial30_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_30/90_trial30_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_31/trial31_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_31/90_trial31_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_32/trial32_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_32/90_trial32_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_33/trial33_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_33/90_trial33_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_34/trial34_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_34/90_trial34_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_35/trial35_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_35/90_trial35_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_36/trial36_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_36/90_trial36_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_37/trial37_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_37/90_trial37_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_38/trial38_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_38/90_trial38_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_39/trial39_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_39/90_trial39_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_40/trial40_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_40/90_trial40_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_41/trial41_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_41/90_trial41_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_42/trial42_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_42/90_trial42_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_43/trial43_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_43/90_trial43_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_44/trial44_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_44/90_trial44_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_45/trial45_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_45/90_trial45_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_46/trial46_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_46/90_trial46_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_47/trial47_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_47/90_trial47_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_48/trial48_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_48/90_trial48_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_49/trial49_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_49/90_trial49_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_50/trial50_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_50/90_trial50_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_51/trial51_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_51/90_trial51_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_52/trial52_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_52/90_trial52_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_53/trial53_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_53/90_trial53_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_54/trial54_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_54/90_trial54_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_55/trial55_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_55/90_trial55_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_56/trial56_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_56/90_trial56_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_57/trial57_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_57/90_trial57_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_58/trial58_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_58/90_trial58_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_59/trial59_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_59/90_trial59_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_60/trial60_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_60/90_trial60_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_61/trial61_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_61/90_trial61_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_62/trial62_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_62/90_trial62_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_63/trial63_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_63/90_trial63_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_64/trial64_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_64/90_trial64_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_65/trial65_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_65/90_trial65_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_66/trial66_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_66/90_trial66_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_67/trial67_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_67/90_trial67_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_68/trial68_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_68/90_trial68_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_69/trial69_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_69/90_trial69_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_70/trial70_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_70/90_trial70_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_71/trial71_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_71/90_trial71_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_72/trial72_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_72/90_trial72_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_73/trial73_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_73/90_trial73_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_74/trial74_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_74/90_trial74_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_75/trial75_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_75/90_trial75_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_76/trial76_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_76/90_trial76_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_77/trial77_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_77/90_trial77_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_78/trial78_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_78/90_trial78_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_79/trial79_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_79/90_trial79_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_80/trial80_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_80/90_trial80_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_81/trial81_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_81/90_trial81_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_82/trial82_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_82/90_trial82_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/trial_83/trial83_decam_convolved*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_83/90_trial83_decam_convolved*.fits 
