rm /Volumes/rliu/jedisim_grid/90_trial_0/90_trial0_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_0/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_1/90_trial1_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_1/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_2/90_trial2_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_2/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_3/90_trial3_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_3/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_4/90_trial4_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_4/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_5/90_trial5_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_5/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_6/90_trial6_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_6/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_7/90_trial7_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_7/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_8/90_trial8_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_8/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_9/90_trial9_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_9/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_10/90_trial10_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_10/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_11/90_trial11_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_11/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_12/90_trial12_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_12/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_13/90_trial13_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_13/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_14/90_trial14_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_14/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_15/90_trial15_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_15/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_16/90_trial16_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_16/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_17/90_trial17_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_17/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_18/90_trial18_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_18/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_19/90_trial19_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_19/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_20/90_trial20_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_20/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_21/90_trial21_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_21/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_22/90_trial22_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_22/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_23/90_trial23_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_23/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_24/90_trial24_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_24/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_25/90_trial25_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_25/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_26/90_trial26_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_26/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_27/90_trial27_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_27/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_28/90_trial28_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_28/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_29/90_trial29_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_29/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_30/90_trial30_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_30/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_31/90_trial31_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_31/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_32/90_trial32_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_32/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_33/90_trial33_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_33/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_34/90_trial34_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_34/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_35/90_trial35_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_35/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_36/90_trial36_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_36/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_37/90_trial37_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_37/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_38/90_trial38_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_38/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_39/90_trial39_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_39/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_40/90_trial40_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_40/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_41/90_trial41_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_41/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_42/90_trial42_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_42/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_43/90_trial43_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_43/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_44/90_trial44_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_44/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_45/90_trial45_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_45/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_46/90_trial46_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_46/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_47/90_trial47_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_47/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_48/90_trial48_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_48/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_49/90_trial49_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_49/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_50/90_trial50_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_50/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_51/90_trial51_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_51/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_52/90_trial52_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_52/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_53/90_trial53_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_53/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_54/90_trial54_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_54/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_55/90_trial55_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_55/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_56/90_trial56_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_56/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_57/90_trial57_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_57/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_58/90_trial58_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_58/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_59/90_trial59_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_59/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_60/90_trial60_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_60/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_61/90_trial61_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_61/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_62/90_trial62_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_62/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_63/90_trial63_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_63/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_64/90_trial64_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_64/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_65/90_trial65_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_65/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_66/90_trial66_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_66/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_67/90_trial67_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_67/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_68/90_trial68_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_68/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_69/90_trial69_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_69/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_70/90_trial70_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_70/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_71/90_trial71_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_71/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_72/90_trial72_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_72/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_73/90_trial73_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_73/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_74/90_trial74_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_74/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_75/90_trial75_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_75/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_76/90_trial76_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_76/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_77/90_trial77_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_77/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_78/90_trial78_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_78/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_79/90_trial79_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_79/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_80/90_trial80_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_80/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_81/90_trial81_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_81/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_82/90_trial82_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_82/convolved/convolved_band*.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_83/90_trial83_HST_convolved.fits 
rm /Volumes/rliu/jedisim_grid/90_trial_83/convolved/convolved_band*.fits 
