python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_83/ 90_trial83_HST.fits /Volumes/rliu/jedisim_grid/90_trial_83/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_82/ 90_trial82_HST.fits /Volumes/rliu/jedisim_grid/90_trial_82/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_81/ 90_trial81_HST.fits /Volumes/rliu/jedisim_grid/90_trial_81/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_80/ 90_trial80_HST.fits /Volumes/rliu/jedisim_grid/90_trial_80/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_79/ 90_trial79_HST.fits /Volumes/rliu/jedisim_grid/90_trial_79/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_78/ 90_trial78_HST.fits /Volumes/rliu/jedisim_grid/90_trial_78/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_77/ 90_trial77_HST.fits /Volumes/rliu/jedisim_grid/90_trial_77/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_76/ 90_trial76_HST.fits /Volumes/rliu/jedisim_grid/90_trial_76/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_75/ 90_trial75_HST.fits /Volumes/rliu/jedisim_grid/90_trial_75/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_74/ 90_trial74_HST.fits /Volumes/rliu/jedisim_grid/90_trial_74/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_73/ 90_trial73_HST.fits /Volumes/rliu/jedisim_grid/90_trial_73/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_72/ 90_trial72_HST.fits /Volumes/rliu/jedisim_grid/90_trial_72/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_71/ 90_trial71_HST.fits /Volumes/rliu/jedisim_grid/90_trial_71/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_70/ 90_trial70_HST.fits /Volumes/rliu/jedisim_grid/90_trial_70/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_69/ 90_trial69_HST.fits /Volumes/rliu/jedisim_grid/90_trial_69/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_68/ 90_trial68_HST.fits /Volumes/rliu/jedisim_grid/90_trial_68/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_67/ 90_trial67_HST.fits /Volumes/rliu/jedisim_grid/90_trial_67/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_66/ 90_trial66_HST.fits /Volumes/rliu/jedisim_grid/90_trial_66/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_65/ 90_trial65_HST.fits /Volumes/rliu/jedisim_grid/90_trial_65/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_64/ 90_trial64_HST.fits /Volumes/rliu/jedisim_grid/90_trial_64/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_63/ 90_trial63_HST.fits /Volumes/rliu/jedisim_grid/90_trial_63/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_62/ 90_trial62_HST.fits /Volumes/rliu/jedisim_grid/90_trial_62/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_61/ 90_trial61_HST.fits /Volumes/rliu/jedisim_grid/90_trial_61/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_60/ 90_trial60_HST.fits /Volumes/rliu/jedisim_grid/90_trial_60/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_59/ 90_trial59_HST.fits /Volumes/rliu/jedisim_grid/90_trial_59/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_58/ 90_trial58_HST.fits /Volumes/rliu/jedisim_grid/90_trial_58/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_57/ 90_trial57_HST.fits /Volumes/rliu/jedisim_grid/90_trial_57/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_56/ 90_trial56_HST.fits /Volumes/rliu/jedisim_grid/90_trial_56/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_55/ 90_trial55_HST.fits /Volumes/rliu/jedisim_grid/90_trial_55/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_54/ 90_trial54_HST.fits /Volumes/rliu/jedisim_grid/90_trial_54/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_53/ 90_trial53_HST.fits /Volumes/rliu/jedisim_grid/90_trial_53/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_52/ 90_trial52_HST.fits /Volumes/rliu/jedisim_grid/90_trial_52/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_51/ 90_trial51_HST.fits /Volumes/rliu/jedisim_grid/90_trial_51/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_50/ 90_trial50_HST.fits /Volumes/rliu/jedisim_grid/90_trial_50/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_49/ 90_trial49_HST.fits /Volumes/rliu/jedisim_grid/90_trial_49/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_48/ 90_trial48_HST.fits /Volumes/rliu/jedisim_grid/90_trial_48/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_47/ 90_trial47_HST.fits /Volumes/rliu/jedisim_grid/90_trial_47/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_46/ 90_trial46_HST.fits /Volumes/rliu/jedisim_grid/90_trial_46/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_45/ 90_trial45_HST.fits /Volumes/rliu/jedisim_grid/90_trial_45/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_44/ 90_trial44_HST.fits /Volumes/rliu/jedisim_grid/90_trial_44/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_43/ 90_trial43_HST.fits /Volumes/rliu/jedisim_grid/90_trial_43/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_42/ 90_trial42_HST.fits /Volumes/rliu/jedisim_grid/90_trial_42/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_41/ 90_trial41_HST.fits /Volumes/rliu/jedisim_grid/90_trial_41/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_40/ 90_trial40_HST.fits /Volumes/rliu/jedisim_grid/90_trial_40/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_39/ 90_trial39_HST.fits /Volumes/rliu/jedisim_grid/90_trial_39/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_38/ 90_trial38_HST.fits /Volumes/rliu/jedisim_grid/90_trial_38/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_37/ 90_trial37_HST.fits /Volumes/rliu/jedisim_grid/90_trial_37/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_36/ 90_trial36_HST.fits /Volumes/rliu/jedisim_grid/90_trial_36/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_35/ 90_trial35_HST.fits /Volumes/rliu/jedisim_grid/90_trial_35/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_34/ 90_trial34_HST.fits /Volumes/rliu/jedisim_grid/90_trial_34/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_33/ 90_trial33_HST.fits /Volumes/rliu/jedisim_grid/90_trial_33/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_32/ 90_trial32_HST.fits /Volumes/rliu/jedisim_grid/90_trial_32/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_31/ 90_trial31_HST.fits /Volumes/rliu/jedisim_grid/90_trial_31/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_30/ 90_trial30_HST.fits /Volumes/rliu/jedisim_grid/90_trial_30/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_29/ 90_trial29_HST.fits /Volumes/rliu/jedisim_grid/90_trial_29/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_28/ 90_trial28_HST.fits /Volumes/rliu/jedisim_grid/90_trial_28/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_27/ 90_trial27_HST.fits /Volumes/rliu/jedisim_grid/90_trial_27/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_26/ 90_trial26_HST.fits /Volumes/rliu/jedisim_grid/90_trial_26/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_25/ 90_trial25_HST.fits /Volumes/rliu/jedisim_grid/90_trial_25/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_24/ 90_trial24_HST.fits /Volumes/rliu/jedisim_grid/90_trial_24/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_23/ 90_trial23_HST.fits /Volumes/rliu/jedisim_grid/90_trial_23/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_22/ 90_trial22_HST.fits /Volumes/rliu/jedisim_grid/90_trial_22/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_21/ 90_trial21_HST.fits /Volumes/rliu/jedisim_grid/90_trial_21/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_20/ 90_trial20_HST.fits /Volumes/rliu/jedisim_grid/90_trial_20/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_19/ 90_trial19_HST.fits /Volumes/rliu/jedisim_grid/90_trial_19/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_18/ 90_trial18_HST.fits /Volumes/rliu/jedisim_grid/90_trial_18/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_17/ 90_trial17_HST.fits /Volumes/rliu/jedisim_grid/90_trial_17/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_16/ 90_trial16_HST.fits /Volumes/rliu/jedisim_grid/90_trial_16/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_15/ 90_trial15_HST.fits /Volumes/rliu/jedisim_grid/90_trial_15/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_14/ 90_trial14_HST.fits /Volumes/rliu/jedisim_grid/90_trial_14/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_13/ 90_trial13_HST.fits /Volumes/rliu/jedisim_grid/90_trial_13/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_12/ 90_trial12_HST.fits /Volumes/rliu/jedisim_grid/90_trial_12/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_11/ 90_trial11_HST.fits /Volumes/rliu/jedisim_grid/90_trial_11/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_10/ 90_trial10_HST.fits /Volumes/rliu/jedisim_grid/90_trial_10/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_9/ 90_trial9_HST.fits /Volumes/rliu/jedisim_grid/90_trial_9/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_8/ 90_trial8_HST.fits /Volumes/rliu/jedisim_grid/90_trial_8/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_7/ 90_trial7_HST.fits /Volumes/rliu/jedisim_grid/90_trial_7/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_6/ 90_trial6_HST.fits /Volumes/rliu/jedisim_grid/90_trial_6/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_5/ 90_trial5_HST.fits /Volumes/rliu/jedisim_grid/90_trial_5/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_4/ 90_trial4_HST.fits /Volumes/rliu/jedisim_grid/90_trial_4/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_3/ 90_trial3_HST.fits /Volumes/rliu/jedisim_grid/90_trial_3/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_2/ 90_trial2_HST.fits /Volumes/rliu/jedisim_grid/90_trial_2/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_1/ 90_trial1_HST.fits /Volumes/rliu/jedisim_grid/90_trial_1/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/90_trial_0/ 90_trial0_HST.fits /Volumes/rliu/jedisim_grid/90_trial_0/ physics_settings/psf_decam.fits
