python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_83/ trial83_HST.fits /Volumes/rliu/jedisim_grid/trial_83/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_82/ trial82_HST.fits /Volumes/rliu/jedisim_grid/trial_82/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_81/ trial81_HST.fits /Volumes/rliu/jedisim_grid/trial_81/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_80/ trial80_HST.fits /Volumes/rliu/jedisim_grid/trial_80/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_79/ trial79_HST.fits /Volumes/rliu/jedisim_grid/trial_79/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_78/ trial78_HST.fits /Volumes/rliu/jedisim_grid/trial_78/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_77/ trial77_HST.fits /Volumes/rliu/jedisim_grid/trial_77/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_76/ trial76_HST.fits /Volumes/rliu/jedisim_grid/trial_76/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_75/ trial75_HST.fits /Volumes/rliu/jedisim_grid/trial_75/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_74/ trial74_HST.fits /Volumes/rliu/jedisim_grid/trial_74/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_73/ trial73_HST.fits /Volumes/rliu/jedisim_grid/trial_73/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_72/ trial72_HST.fits /Volumes/rliu/jedisim_grid/trial_72/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_71/ trial71_HST.fits /Volumes/rliu/jedisim_grid/trial_71/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_70/ trial70_HST.fits /Volumes/rliu/jedisim_grid/trial_70/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_69/ trial69_HST.fits /Volumes/rliu/jedisim_grid/trial_69/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_68/ trial68_HST.fits /Volumes/rliu/jedisim_grid/trial_68/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_67/ trial67_HST.fits /Volumes/rliu/jedisim_grid/trial_67/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_66/ trial66_HST.fits /Volumes/rliu/jedisim_grid/trial_66/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_65/ trial65_HST.fits /Volumes/rliu/jedisim_grid/trial_65/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_64/ trial64_HST.fits /Volumes/rliu/jedisim_grid/trial_64/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_63/ trial63_HST.fits /Volumes/rliu/jedisim_grid/trial_63/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_62/ trial62_HST.fits /Volumes/rliu/jedisim_grid/trial_62/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_61/ trial61_HST.fits /Volumes/rliu/jedisim_grid/trial_61/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_60/ trial60_HST.fits /Volumes/rliu/jedisim_grid/trial_60/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_59/ trial59_HST.fits /Volumes/rliu/jedisim_grid/trial_59/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_58/ trial58_HST.fits /Volumes/rliu/jedisim_grid/trial_58/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_57/ trial57_HST.fits /Volumes/rliu/jedisim_grid/trial_57/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_56/ trial56_HST.fits /Volumes/rliu/jedisim_grid/trial_56/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_55/ trial55_HST.fits /Volumes/rliu/jedisim_grid/trial_55/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_54/ trial54_HST.fits /Volumes/rliu/jedisim_grid/trial_54/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_53/ trial53_HST.fits /Volumes/rliu/jedisim_grid/trial_53/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_52/ trial52_HST.fits /Volumes/rliu/jedisim_grid/trial_52/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_51/ trial51_HST.fits /Volumes/rliu/jedisim_grid/trial_51/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_50/ trial50_HST.fits /Volumes/rliu/jedisim_grid/trial_50/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_49/ trial49_HST.fits /Volumes/rliu/jedisim_grid/trial_49/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_48/ trial48_HST.fits /Volumes/rliu/jedisim_grid/trial_48/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_47/ trial47_HST.fits /Volumes/rliu/jedisim_grid/trial_47/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_46/ trial46_HST.fits /Volumes/rliu/jedisim_grid/trial_46/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_45/ trial45_HST.fits /Volumes/rliu/jedisim_grid/trial_45/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_44/ trial44_HST.fits /Volumes/rliu/jedisim_grid/trial_44/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_43/ trial43_HST.fits /Volumes/rliu/jedisim_grid/trial_43/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_42/ trial42_HST.fits /Volumes/rliu/jedisim_grid/trial_42/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_41/ trial41_HST.fits /Volumes/rliu/jedisim_grid/trial_41/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_40/ trial40_HST.fits /Volumes/rliu/jedisim_grid/trial_40/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_39/ trial39_HST.fits /Volumes/rliu/jedisim_grid/trial_39/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_38/ trial38_HST.fits /Volumes/rliu/jedisim_grid/trial_38/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_37/ trial37_HST.fits /Volumes/rliu/jedisim_grid/trial_37/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_36/ trial36_HST.fits /Volumes/rliu/jedisim_grid/trial_36/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_35/ trial35_HST.fits /Volumes/rliu/jedisim_grid/trial_35/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_34/ trial34_HST.fits /Volumes/rliu/jedisim_grid/trial_34/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_33/ trial33_HST.fits /Volumes/rliu/jedisim_grid/trial_33/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_32/ trial32_HST.fits /Volumes/rliu/jedisim_grid/trial_32/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_31/ trial31_HST.fits /Volumes/rliu/jedisim_grid/trial_31/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_30/ trial30_HST.fits /Volumes/rliu/jedisim_grid/trial_30/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_29/ trial29_HST.fits /Volumes/rliu/jedisim_grid/trial_29/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_28/ trial28_HST.fits /Volumes/rliu/jedisim_grid/trial_28/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_27/ trial27_HST.fits /Volumes/rliu/jedisim_grid/trial_27/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_26/ trial26_HST.fits /Volumes/rliu/jedisim_grid/trial_26/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_25/ trial25_HST.fits /Volumes/rliu/jedisim_grid/trial_25/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_24/ trial24_HST.fits /Volumes/rliu/jedisim_grid/trial_24/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_23/ trial23_HST.fits /Volumes/rliu/jedisim_grid/trial_23/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_22/ trial22_HST.fits /Volumes/rliu/jedisim_grid/trial_22/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_21/ trial21_HST.fits /Volumes/rliu/jedisim_grid/trial_21/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_20/ trial20_HST.fits /Volumes/rliu/jedisim_grid/trial_20/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_19/ trial19_HST.fits /Volumes/rliu/jedisim_grid/trial_19/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_18/ trial18_HST.fits /Volumes/rliu/jedisim_grid/trial_18/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_17/ trial17_HST.fits /Volumes/rliu/jedisim_grid/trial_17/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_16/ trial16_HST.fits /Volumes/rliu/jedisim_grid/trial_16/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_15/ trial15_HST.fits /Volumes/rliu/jedisim_grid/trial_15/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_14/ trial14_HST.fits /Volumes/rliu/jedisim_grid/trial_14/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_13/ trial13_HST.fits /Volumes/rliu/jedisim_grid/trial_13/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_12/ trial12_HST.fits /Volumes/rliu/jedisim_grid/trial_12/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_11/ trial11_HST.fits /Volumes/rliu/jedisim_grid/trial_11/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_10/ trial10_HST.fits /Volumes/rliu/jedisim_grid/trial_10/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_9/ trial9_HST.fits /Volumes/rliu/jedisim_grid/trial_9/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_8/ trial8_HST.fits /Volumes/rliu/jedisim_grid/trial_8/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_7/ trial7_HST.fits /Volumes/rliu/jedisim_grid/trial_7/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_6/ trial6_HST.fits /Volumes/rliu/jedisim_grid/trial_6/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_5/ trial5_HST.fits /Volumes/rliu/jedisim_grid/trial_5/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_4/ trial4_HST.fits /Volumes/rliu/jedisim_grid/trial_4/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_3/ trial3_HST.fits /Volumes/rliu/jedisim_grid/trial_3/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_2/ trial2_HST.fits /Volumes/rliu/jedisim_grid/trial_2/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_1/ trial1_HST.fits /Volumes/rliu/jedisim_grid/trial_1/ physics_settings/psf_decam.fits
python jediconvolver.py /Volumes/rliu/jedisim_grid/trial_0/ trial0_HST.fits /Volumes/rliu/jedisim_grid/trial_0/ physics_settings/psf_decam.fits